### ISSUE TITLE
Can MR prevent malware using signed driver from modifying ntoskrnl.exe in kernel mode?

### ISSUE THREAD

**Issue by L1B0** [IgorKorkin/MemoryRanger#2]
Hi Igor Korkin, I have read your paper that published in S&P 2021 recently.
As well as I'm interested in whether the MemoryRanger can prevent malware from modifying ntoskrnl.exe? Because malware can disable the Register and Process callback by modifying the SupportsObjectCallbacks flag or Callback List, and then malware can terminate AV or modify register key to disable AV. But MR is designed to just protect the PPL of process, is that correct? Maybe I miss some details.

Thanks!

**Comment by IgorKorkin** [comment]
Hi @L1B0 ! Thank you for your message! 

Yes, MemoryRanger can protect ntoskrnl.exe from being modified by malware.
The mentioned PPL case is just one of the cases of MemoryRanger customization.

MemoryRanger is designed to prevent any illegal access to the kernel code and data memory. MemoryRanger runs kernel drivers into isolated memory enclaves. 

Here are more examples of MemoryRanger customization:
1. MemoryRanger prevents illegal access to the memory allocated by drivers, link - https://igorkorkin.blogspot.com/2018/12/divide-et-impera-memoryranger-runs.html
2. MemoryRanger prevent illegal FILE_OBJECT hijacking and TOKEN hijacking
Link - https://igorkorkin.blogspot.com/2019/04/memoryranger-prevents-hijacking.html
Link - https://igorkorkin.blogspot.com/2021/05/kernel-hijacking-is-not-option.html

MemoryRanger is a long-term project, you can find more demos here - https://www.youtube.com/watch?v=NK_h9nwa3Vo&list=PL0Aerbf3kwUJB8VtLJkiK_PPztaqOvmmQ&ab_channel=BlackHat
![image](https://user-images.githubusercontent.com/10939751/145684436-2cb9c49f-85af-4003-a4b0-1a2195d50734.png)

**Comment by L1B0** [comment]
Hi @IgorKorkin !
Thanks for your detailed reply! I'll learn from those links.

**Comment by L1B0** [comment]
Hi @IgorKorkin ! 
I read the MemoryMonRWX paper(2017), and its performance degradation is about 10%. As well as MemoryRanger is about 50%, which is higher. My question is why use MemoryRanger which puts drivers into enclaves, because MemoryMonRWX can also monitor the memory of protected process to prevent malware from modifying the PPL flag.
Thanks:-)

**Comment by IgorKorkin** [comment]
Hi @L1B0!
You know the question about performance degradation is always tricky. 😀 
Actually, if the tiny PC will be used for performance assessment - the higher degradation we will see.
Now I have a powerful PC (i9-11900 + 64GB RAM) and I can see that the degradation is not so big.
Also, all my projects are proofs-of-concept and they are not designed to be faster. 

The key difference between MemoryMonRWX-project and MemoryRanger-project is that MemoryMonRWX supports just one additional memory enclave for one 'suspicious' driver only, while MemoryRanger allocates memory enclave in runtime. 
For example, MemoryRanger can isolate three 'suspicious' drivers from each other, while MemoryMonRWX cannot do this, it can process only one driver.

MemoryRanger is an advanced version of MemoryMonRWX, which I do not use now. 
I use MemoryRanger for all my current research works. 

Thank you for all your questions! 

PS Also, we can discuss more questions using WeChat or WeLink.

**Comment by L1B0** [comment]
Hi @IgorKorkin !
Thanks for your detailed reply!
That's great to discuss questions using WeChat, I have sent my wechat id to your gmail, please check it.
Thanks:-)
